### ISSUE TITLE
Add option to install freeIPA server CA certificate to Java keystores on clients

### ISSUE THREAD

**Issue by CodingSpiderFox** [helpscout/chef-ipa#3]
Hello,

I want to use freeIPA as central authentication provider for all my development environment's services (Jenkins, Artifactory, Sonar, etc.)

Those services might run on different machines. In order to let these services authenticate against the LDAP  of freeIPA, I want to make the connection to the IPA server with the LDAP service over TLS (LDAPS, Port 636).
As Jenkins and Artifactory are Java applications, the require the CA cert to be trusted in the machine's Java keystore before the LDAPS connection can be established. 

I would save me a lot of work if I could enroll the CA cert of the freeIPA server to the Java keystore on my machines using this chef cookbook.

Best regards
Chris

**Comment by jrb** [comment]
Hi Chris- 
I'm afraid that's probably outside the scope of this cookbook at this time. Your best bet might be to use the `java` cookbook on the supermarket though. It provides a `java_certificate` lwrp for managing certificates in arbitrary keystores. https://github.com/agileorbit-cookbooks/java#java_certificate

After a host has been enrolled in IPA, the IPA CA Certificate is available at `/etc/ipa/ca.crt`.
